# Compile a narrowly patched copy; never mutate the shared Pub cache. Review
# this adapter when upgrading flutter_inappwebview_windows (currently 0.6.0).
function(simple_live_webview_diagnostics)
  set(plugin flutter_inappwebview_windows_plugin)
  get_target_property(plugin_dir ${plugin} SOURCE_DIR)
  get_target_property(plugin_sources ${plugin} SOURCES)
  set(relative_source webview_environment/webview_environment_manager.cpp)
  file(READ "${plugin_dir}/${relative_source}" source)
  set(original [=[result_->Error("0", "Cannot create WebViewEnvironment: " + getHRMessage(errorCode));]=])
  set(replacement [=[result_->Error(std::to_string(static_cast<unsigned long>(errorCode)), "WebView2 environment creation failed");]=])
  string(FIND "${source}" "${original}" anchor)
  if(anchor EQUAL -1)
    message(FATAL_ERROR "Review WebView2 HRESULT adapter for the new plugin version")
  endif()
  string(REPLACE "${original}" "${replacement}" patched "${source}")
  set(patched_dir "${CMAKE_CURRENT_BINARY_DIR}/webview_diagnostics")
  file(MAKE_DIRECTORY "${patched_dir}")
  set(patched_source "${patched_dir}/webview_environment_manager.cpp")
  file(WRITE "${patched_source}" "${patched}")

  set(sources)
  set(replaced FALSE)
  foreach(item IN LISTS plugin_sources)
    if(item STREQUAL relative_source OR item STREQUAL "${plugin_dir}/${relative_source}")
      list(APPEND sources "${patched_source}")
      set(replaced TRUE)
    elseif(IS_ABSOLUTE "${item}" OR item MATCHES "^\\$<")
      list(APPEND sources "${item}")
    else()
      list(APPEND sources "${plugin_dir}/${item}")
    endif()
  endforeach()
  if(NOT replaced)
    message(FATAL_ERROR "Cannot locate WebView2 environment manager in plugin sources")
  endif()
  set_property(TARGET ${plugin} PROPERTY SOURCES "${sources}")
  # Resolve the copied source's original relative includes.
  target_include_directories(${plugin} PRIVATE "${plugin_dir}/webview_environment")
endfunction()
